version: "2"

services:
  db:
    image: mysql:5.5.54
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root,
      MYSQL_PASSWORD: root,
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql:
    external: true
